apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql
  namespace: infra
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.3
  annotations:
    meta.helm.sh/release-name: postgres
    meta.helm.sh/release-namespace: database
data:
  password: UEBzdzByZDE=
  postgres-password: UEBzdzByZDE=
type: Opaque